In [21]:
import pandas as pd

In [22]:
dataset = pd.read_csv("datasets/datos-demograficos-visitas-tratamientos-missing-imputation-mean-average_last_next_values.csv")

In [23]:
dataset.head()

Id   Sexo        Raza  Peso_nacimiento  Semanas_gestacion Lugar_nacimiento  \
0   1  Mujer  Caucasiana         2.849938          37.450408          Navarra   
1   1  Mujer  Caucasiana         2.849938          37.450408          Navarra   
2   1  Mujer  Caucasiana         2.849938          37.450408          Navarra   
3   1  Mujer  Caucasiana         2.849938          37.450408          Navarra   
4   1  Mujer  Caucasiana         2.849938          37.450408          Navarra   

  Lugar_residencia                             Grupo_diagnostico  \
0          Navarra  Enfermedades sistémicas que afectan al riñón   
1          Navarra  Enfermedades sistémicas que afectan al riñón   
2          Navarra  Enfermedades sistémicas que afectan al riñón   
3          Navarra  Enfermedades sistémicas que afectan al riñón   
4          Navarra  Enfermedades sistémicas que afectan al riñón   

  Dx_histologico Patologia_extrarrenal         ...           \
0             No                    No         ...            
1             No                    No         ...            
2             No                    No         ...            
3             No                    No         ...            
4             No                    No         ...            

  Sonda_nasogastrica  Suplementos_nutricionales  Fluorhidrocortisona  \
0                 No                         Sí                   No   
1                 No                         Sí                   No   
2                 No                         No                   No   
3                 No                         No                   No   
4                 No                         No                   No   

   hipotensor_IECA_ARA  IECA  ARA  Aporte_calcio  Tiempo_evolucion  \
0                   No    Sí   No             No              0.85   
1                   No    Sí   No             No              1.12   
2                   No    Sí   No             No              2.96   
3                   No    Sí   No             No              3.86   
4                   No    Sí   No             No              4.85   

  Edad_visita  Filtrado_glomerular  
0        4.01                32.24  
1        4.28                41.45  
2        6.12                51.87  
3        7.02                48.62  
4        8.01                46.93  

[5 rows x 60 columns]

In [24]:
id_visits = dataset["Id"].value_counts()

In [26]:
id_visits.shape

(1559,)

In [15]:
ids= id_visits.index.values

In [16]:
visitas= id_visits.values

In [17]:
ids, visitas

(array([663, 684, 136, ..., 582, 548, 327]),
 array([13, 13, 12, ...,  1,  1,  1]))

In [20]:
for i in zip(ids, visitas):
    print(i)

(663, 13)
(684, 13)
(136, 12)
(138, 12)
(66, 12)
(264, 12)
(181, 11)
(191, 11)
(215, 11)
(279, 11)
(283, 11)
(272, 11)
(173, 11)
(224, 11)
(158, 11)
(801, 11)
(179, 11)
(205, 11)
(221, 11)
(233, 11)
(190, 11)
(457, 11)
(262, 11)
(238, 11)
(337, 11)
(334, 11)
(201, 11)
(149, 11)
(159, 11)
(282, 11)
(390, 11)
(18, 11)
(107, 11)
(1, 11)
(306, 11)
(59, 11)
(139, 11)
(437, 10)
(589, 10)
(659, 10)
(374, 10)
(184, 10)
(848, 10)
(445, 10)
(340, 10)
(486, 10)
(429, 10)
(862, 10)
(904, 10)
(737, 10)
(550, 10)
(534, 10)
(693, 10)
(294, 10)
(220, 10)
(471, 10)
(576, 10)
(568, 10)
(111, 10)
(88, 10)
(129, 10)
(769, 10)
(48, 10)
(403, 10)
(399, 10)
(650, 10)
(33, 10)
(56, 10)
(519, 10)
(627, 10)
(52, 10)
(617, 9)
(1051, 9)
(681, 9)
(734, 9)
(645, 9)
(368, 9)
(951, 9)
(569, 9)
(806, 9)
(922, 9)
(887, 9)
(432, 9)
(792, 9)
(768, 9)
(752, 9)
(50, 9)
(648, 9)
(644, 9)
(35, 9)
(47, 9)
(131, 9)
(303, 9)
(319, 9)
(528, 9)
(1014, 9)
(479, 9)
(643, 9)
(549, 9)
(707, 9)
(865, 9)
(857, 9)
(837, 9)
(1044, 9)
(81

In [27]:
id_visits = pd.read_csv(
    "datasets/datos-id-visitas.csv"
)

ids = id_visits["Id"].values
visits = id_visits["Visits"].values

In [29]:
visits

array([11,  3,  5, ...,  2,  2,  2])

In [30]:
id_visits

Id  Visits
0        1      11
1        3       3
2        5       5
3        7       5
4        8       4
5       11       2
6       12       4
7       13       8
8       14       6
9       15       5
10      16       6
11      17       6
12      18      11
13      19       3
14      20       6
15      21       2
16      22       2
17      23       4
18      24       3
19      25       4
20      26       5
21      27       5
22      28       5
23      29       7
24      30       3
25      32       9
26      33      10
27      34       2
28      35       9
29      36       2
...    ...     ...
1470  1949       2
1471  1950       2
1472  1952       2
1473  1953       2
1474  1954       2
1475  1956       2
1476  1957       2
1477  1958       2
1478  1959       2
1479  1961       2
1480  2005       2
1481  2006       2
1482  2012       2
1483  2025       2
1484  2027       2
1485  2033       3
1486  2035       2
1487  2037       2
1488  2050       4
1489  2051       3
1490  2054       3
1491  2056       3
1492  2059       2
1493  2072       2
1494  2073       3
1495  2088       2
1496  2095       3
1497  2096       2
1498  2106       2
1499  2107       2

[1500 rows x 2 columns]

In [31]:
from sklearn.model_selection import StratifiedKFold

In [33]:
kfold = StratifiedKFold(n_splits= 10, shuffle=True)

In [34]:
for train_index, test_index in kfold.split(ids, visits):
    print(train_index, test_index)

[   0    2    3 ... 1497 1498 1499] [   1   12   18   21   35   44   45   50   53   68   93   94   96  100
  103  105  108  123  124  153  154  166  169  176  191  196  203  205
  220  233  237  252  256  268  281  282  305  316  319  320  322  323
  332  335  343  368  379  420  422  429  432  439  446  451  463  474
  494  508  531  532  541  545  562  563  568  572  573  583  588  592
  603  604  634  637  639  648  658  687  693  709  723  725  731  732
  761  776  780  784  794  795  802  814  817  851  856  865  874  876
  888  893  894  895  912  924  937  940  944  983  986  994 1006 1007
 1012 1013 1015 1019 1023 1041 1045 1046 1051 1055 1057 1077 1089 1124
 1130 1138 1156 1162 1225 1253 1262 1269 1281 1286 1288 1296 1315 1323
 1334 1342 1363 1364 1376 1387 1410 1418 1441 1452 1461 1466 1474 1475
 1480]
[   0    1    2 ... 1497 1498 1499] [  10   26   33   38   42   47   48   60   76  112  116  133  151  168
  173  182  199  224  228  229  230  235  241  247  308  314  315  31

/home/ogreyesp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [35]:
visits[test_index]

array([ 3, 10,  4,  2,  3,  2, 11, 11, 10,  4, 11,  8,  3,  3,  9,  4,  9,
        8,  5,  3,  2,  2,  6,  3,  7,  2,  6,  4,  3,  6,  2,  2,  5, 10,
        5,  2,  2,  4,  4,  5,  5,  3,  2,  6,  9,  7,  5,  5,  5,  3,  3,
        2,  8,  5,  5,  4,  4,  4,  5,  9,  5,  8,  7,  3,  9,  2,  8,  2,
        7,  3,  2,  6,  2,  7,  4,  6,  2,  7,  7,  2,  6,  3,  7,  5,  7,
        2,  6,  6,  2,  6,  6,  8,  5,  3,  3,  2,  4,  4,  5,  5,  3,  4,
        2,  2,  4,  3,  4,  3,  4,  2,  4,  5,  4,  4,  2,  3,  4,  4,  3,
        3,  2,  3,  2,  5,  3,  3,  3,  3,  3,  2,  2,  2,  2,  3,  2,  2,
        2,  2,  2,  2,  2,  2,  4,  3])

In [39]:
import numpy as np
np.sum(visits[train_index]==13)

2

In [41]:
ids[train_index]
ids[test_index]

array([  30,   56,   73,   81,   84,  113,  139,  173,  184,  216,  224,
        251,  271,  301,  310,  316,  333,  339,  351,  355,  365,  371,
        381,  394,  408,  422,  442,  454,  465,  491,  497,  498,  511,
        519,  559,  561,  562,  571,  586,  603,  609,  621,  637,  641,
        643,  662,  665,  667,  668,  676,  697,  759,  788,  793,  843,
        844,  845,  853,  878,  887,  888,  889,  941,  945,  951,  961,
        974,  990, 1010, 1012, 1035, 1045, 1050, 1073, 1086, 1108, 1109,
       1118, 1123, 1136, 1143, 1146, 1153, 1157, 1173, 1207, 1208, 1214,
       1235, 1258, 1279, 1286, 1292, 1320, 1368, 1369, 1379, 1383, 1408,
       1414, 1421, 1439, 1453, 1457, 1458, 1479, 1515, 1528, 1535, 1542,
       1552, 1572, 1579, 1584, 1592, 1599, 1601, 1623, 1644, 1649, 1661,
       1678, 1690, 1692, 1711, 1736, 1745, 1766, 1769, 1803, 1811, 1826,
       1829, 1844, 1874, 1884, 1891, 1926, 1928, 1934, 1939, 2006, 2050,
       2054])

In [45]:
dataset[dataset["Id"].isin(ids[train_index])].shape

(6045, 60)

In [50]:
dataset[dataset["Id"].isin(ids[test_index])].shape

(626, 60)

In [47]:
dataset.shape

(6730, 60)

In [48]:
dataset.columns

Index(['Id', 'Sexo', 'Raza', 'Peso_nacimiento', 'Semanas_gestacion',
       'Lugar_nacimiento', 'Lugar_residencia', 'Grupo_diagnostico',
       'Dx_histologico', 'Patologia_extrarrenal', 'Antecedentes_familiares',
       'Edad_diagnostico', 'Peso', 'Talla', 'SC', 'IMC', 'Urea', 'Cr', 'HTA',
       'PAS', 'PAD', 'Hto', 'Hb', 'Ferritina', 'Indice_transferrina', 'Ca',
       'P', 'PTH', 'X25.OH', 'Na', 'K', 'HCO3', 'Proteinuria',
       'Microalbuminuria', 'BUN', 'Estatinas', 'Quelantes_calcio',
       'Quelantes_libres_calcio', 'Vitamina_D3', 'dihidroxivintamina',
       'hidroxivitamina', 'otra_vitamina', 'Fe', 'EPO', 'Bicarbonato',
       'Resinas_intercambio', 'Cloruro_Na', 'HGH', 'Acido_folico',
       'Alopurinol', 'Sonda_nasogastrica', 'Suplementos_nutricionales',
       'Fluorhidrocortisona', 'hipotensor_IECA_ARA', 'IECA', 'ARA',
       'Aporte_calcio', 'Tiempo_evolucion', 'Edad_visita',
       'Filtrado_glomerular'],
      dtype='object')

In [52]:
from sklearn.preprocessing import StandardScaler
columns_numeric = pd.read_csv(
    "datasets/original_columns_numeric.csv"
)["Column"].values

scaler = StandardScaler()
scaler.fit(dataset[columns_numeric])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [57]:
dataset[columns_numeric]= scaler.transform(dataset[columns_numeric])

In [56]:
columns_numeric.shape

(26,)

In [58]:
dataset

Id    Sexo        Raza  Peso_nacimiento  Semanas_gestacion  \
0        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
1        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
2        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
3        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
4        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
5        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
6        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
7        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
8        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
9        1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
10       1   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
11       3  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
12       3  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
13       3  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
14       5  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
15       5  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
16       5  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
17       5  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
18       5  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
19       7  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
20       7  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
21       7  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
22       7  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
23       7  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
24       8   Mujer  Caucasiana     8.159954e-01      -9.617737e-15   
25       8   Mujer  Caucasiana     8.159954e-01      -9.617737e-15   
26       8   Mujer  Caucasiana     8.159954e-01      -9.617737e-15   
27       8   Mujer  Caucasiana     8.159954e-01      -9.617737e-15   
28      11   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
29      11   Mujer  Caucasiana     2.415497e-15      -9.617737e-15   
...    ...     ...         ...              ...                ...   
6700  2050  Hombre  Caucasiana     3.989888e-01       1.150356e+00   
6701  2050  Hombre  Caucasiana     3.989888e-01       1.150356e+00   
6702  2050  Hombre  Caucasiana     3.989888e-01       1.150356e+00   
6703  2051  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6704  2051  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6705  2051  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6706  2054  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6707  2054  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6708  2054  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6709  2056  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6710  2056  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6711  2056  Hombre  Caucasiana     2.415497e-15      -9.617737e-15   
6712  2059  Hombre       Árabe     2.415497e-15      -9.617737e-15   
6713  2059  Hombre       Árabe     2.415497e-15      -9.617737e-15   
6714  2072  Hombre     Hispana     5.440346e-01      -2.032206e-01   
6715  2072  Hombre     Hispana     5.440346e-01      -2.032206e-01   
6716  2073  Hombre     Hispana    -9.054058e-02      -1.105605e+00   
6717  2073  Hombre     Hispana    -9.054058e-02      -1.105605e+00   
6718  2073  Hombre     Hispana    -9.054058e-02      -1.105605e+00   
6719  2088   Mujer  Caucasiana    -3.806321e-01      -2.032206e-01   
6720  2088   Mujer  Caucasiana    -3.806321e-01      -2.032206e-01   
6721  2095  Hombre  Caucasiana    -3.262399e-01      -2.032206e-01   
6722  2095  Hombre  Caucasiana    -3.262399e-01      -2.032206e-01   
6723  2095  Hombre  Caucasiana    -3.262399e-01      -2.032206e-01   
6724  2096  Hombre  Caucasiana    -3.625014e-01       1.150356e+00   
6725  2096  Hombre